name: CI Unit Test

on:
  push:
    branches: [ master ]

jobs:
  unittest:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      # 현재 레포지토리 코드 업로드
      - uses: actions/checkout@v2

      # 정상적으로 clone 되었는지 확인
      - name: Run pwd
        run: pwd
      - name: Check directory
        run: ls -al
      
      # Node js 설치
      - name: SetUp Node js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # 유닛 테스트
      - name: Run Unit Test
        run: |
          npm install
          npm test