name: CD Deploy

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]

jobs:
  unittest:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      # 현재 레포지토리 코드 업로드
      - uses: actions/checkout@v2

      # 정상적으로 clone 되었는지 확인
      - name: Run pwd
        run: pwd
      - name: Check directory
        run: ls -al

      # Node js 설치
      - name: SetUp Node js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # 유닛 테스트
      - name: Run Unit Test
        run: |
          npm install
          npm run test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: unittest

    steps:
      # 현재 레포지토리 코드 업로드
      - name: Checkout my code
        uses: actions/checkout@v2

      # Node js 설치
      - name: SetUp Node js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # 리액트 빌드
      - name: React Build
        run: |
          npm install
          npm run build

      # Docker 설정
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: knunslab/lab-server

      # Docker Hub 로그인, GitHub Secret 사용
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Docker Build, Docker Hub Push
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labes }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    # 배포는 추후 작성
    steps:
      # 현재 레포지토리 코드 업로드
      - name: Checkout my code
        uses: actions/checkout@v2

      # 정상적으로 clone 되었는지 확인
      - name: Run pwd
        run: pwd
      - name: Check directory
        run: ls -al